### ISSUE TITLE
Catching custom exceptions?

### ISSUE THREAD

**Issue by magnars** [andersfurseth/jiffy#1]
Hi! I started work on the `zone-id` namespace, thinking that would be an easy place to start. However, I quickly ran into an issue with exceptions.

The generated code for ZoneRulesException looks like this:

```
(defn ZoneRulesException
  ([s] (ZoneRulesException s nil nil))
  ([s m] (ZoneRulesException s m nil))
  ([s m e] (ex-info s (or m {}))))
```

The `normalized`-method needs to catch `ZoneRulesException`, looking like this:

```
(defn -normalized [this]
  (try
    (let [rules (.getRules this)]
      (if (.isFixedOffset rules)
        (.getOffset rules Instant/EPOCH)
        this))
    (catch ZoneRulesException e
      this)))  ;; invalid ZoneRegion is not important to this method
```

So, a plain old ex-info exception won't do. How do we handle that?

**Comment by andersfurseth** [comment]
Having given this much thought, but how about make the custom exceptions in jiffy (there are three of them) to records for now?

If interop from Javascript is a concern down the line we might consider extending js/Error (ala what ex-info does).

**Comment by andersfurseth** [comment]
I just noticed java.time's three exceptions forms an hierarchy

* `ZoneRulesException` extends `DateTimeException`
* `UnsupportedTemporalTypeException` extends `DateTimeException`
* `DateTimeException` is the base (albeit concrete) class (extending `RuntimeException`)

The java.time-implementation is riddled with catch'es of `DateTimeException`, so this control flow needs to be reflected somehow. My initial though was representing this hierarchy with a marker protocol (e.g. `jiffy.date-time-exception/DateTimeException`), and having all concrete exception records extend this protocol. Unfortunately, Clojurescript's try/catch dispatches on type and not something akin to a `satisfies?` check.

As far as I can see we're either 1) stuck with rolling our own try/catch which dispatches on both type and `satifisies?`, or 2) replace every try/catch of `DateTimeException` with a try/catch that includes the other two exception subclasses as well.

Nevertheless, we'll have to represent the exceptions with records/types rather than ex-info.

**Comment by magnars** [comment]
How about a custom try-catch macro that resolves a `DateTimeException`-catch into all three?

**Comment by magnars** [comment]
In other words, a custom `try`-macro that expands in a regular `try`-macro with handlers for the subclasses of `DateTimeException` if it is listed?

**Comment by andersfurseth** [comment]
Sounds good 👍

**Comment by andersfurseth** [comment]
Custom `try*` macro is now available. See [contribution guideline](https://github.com/andersfurseth/jiffy/blob/master/CONTRIBUTING.md) for documentation.
